name: Test sync settings
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: git rm --cached .github/settings.yml ; git add .github/settings.yml ; touch .github/settings.yml ; git status
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync settings
          commit_options: '--allow-empty'
          file_pattern: .github/settings.yml
          skip_dirty_check: true
          commit_user_name: micronaut-build
          commit_user_email: ${{ secrets.MICRONAUT_BUILD_EMAIL }}
          commit_author: micronaut-build <${{ secrets.MICRONAUT_BUILD_EMAIL }}>